/-
  WikifunctionsSpecs.lean — Mathlib oracles for the WikiLean ↔ Wikifunctions addressable set.

  For each Wikifunctions function that has a WikiLean Mathlib mapping (joined on the
  Wikidata QID via the `wikifunctionswiki` sitelink), this file pins an oracle — the
  value the Wikifunction is meant to return — and states its defining properties.

  Every block was machine-checked individually against Mathlib (lake env lean, targeted
  imports), then this concatenated file was built as a whole. ZERO `sorry`, ZERO axiom
  cheats; concrete checks use kernel `decide` (ℕ/ℤ tiers) or native `#guard` (Float tier),
  never `native_decide` in proofs.

  Tiers:
    composite_provable — computable/decidable ℕ/ℤ oracle; conformance is provable in-kernel.
    oracle_testable    — computable oracle used as differential-test ground truth:
                         * ℚ/ℤ oracles (exact arithmetic), and
                         * Float oracles for float64 Wikifunctions: Lean `Float` is IEEE-754
                           binary64 (`@[extern]` to libm), so `Z*_spec : Float → …` is
                           `#eval`-comparable bit-for-bit to the live function. Each carries
                           a `noncomputable` `Z*_ideal : ℝ → …` documenting the exact
                           mathematical function it approximates.
    spec_only          — noncomputable real oracle only (e.g. arbitrary-precision Gamma).

  Auto-generated by catalog/wikifunctions_specs.py + the build-fix workflow.
-/

import Mathlib.Algebra.BigOperators.Group.List.Basic
import Mathlib.Algebra.GCDMonoid.Nat
import Mathlib.Algebra.Group.Nat.Defs
import Mathlib.Analysis.SpecialFunctions.Gamma.Basic
import Mathlib.Analysis.SpecialFunctions.Log.Base
import Mathlib.Analysis.SpecialFunctions.Log.Basic
import Mathlib.Analysis.SpecialFunctions.Log.NegMulLog
import Mathlib.Analysis.SpecialFunctions.Pow.Real
import Mathlib.Data.Complex.Basic
import Mathlib.Data.Finset.Powerset
import Mathlib.Data.Int.Basic
import Mathlib.Data.Matrix.Diagonal
import Mathlib.Data.Nat.Choose.Basic
import Mathlib.Data.Nat.Factorial.Basic
import Mathlib.Data.Nat.Factorial.BigOperators
import Mathlib.Data.Nat.Fib.Basic
import Mathlib.Data.Nat.GCD.Basic
import Mathlib.Data.Nat.Prime.Defs
import Mathlib.Data.Nat.Totient
import Mathlib.Data.Rat.Defs
import Mathlib.Data.ZMod.Basic
import Mathlib.LinearAlgebra.AffineSpace.AffineMap
import Mathlib.NumberTheory.Divisors
import Mathlib.NumberTheory.PythagoreanTriples
import Mathlib.Probability.ConditionalProbability
import Mathlib.RingTheory.Coprime.Lemmas
import Mathlib.Tactic

open scoped BigOperators

/- ======================================================================== -/
/- TIER 1 — composite_provable (computable/decidable ℕ/ℤ oracle; provable in-kernel) -/
/- ======================================================================== -/

/- ----- Z12427  (Q49008)  [faithful] ----- -/
/-- Wikifunctions Z12427 "is prime" — Wikidata Q49008.
    Oracle: `Nat.Prime` (decidable via `Nat.decidablePrime`).
    Signature (Natural number) -> Boolean ↦ `fun n => decide (Nat.Prime n)`. -/
def Z12427_spec (n : ℕ) : Bool := decide (Nat.Prime n)

-- Sanity: agrees with the elementary divisor-search characterisation.
example (n : ℕ) : Z12427_spec n = true ↔ (2 ≤ n ∧ ∀ m, 2 ≤ m → m < n → ¬ m ∣ n) := by
  simp only [Z12427_spec, decide_eq_true_eq]; exact Nat.prime_def_lt'

-- Concrete evaluations (kernel-decidable):
example : Z12427_spec 7 = true  := by decide
example : Z12427_spec 1 = false := by decide
example : Z12427_spec 9 = false := by decide

/- ----- Z13612  (Q131752)  [wrong_target] ----- -/
/-- Wikifunctions Z13612 "greatest common divisor" — Wikidata Q131752.
Signature: (ℕ, ℕ) → ℕ.
Oracle: `Nat.gcd` (computable on ℕ; defined in Lean core, re-exported via
`Mathlib.Algebra.GCDMonoid.Nat`).
NOTE: the WikiLean primary_decl `GCDMonoid` (Mathlib/Algebra/GCDMonoid/Basic.lean)
is a TYPECLASS, not the operation; the faithful oracle is `Nat.gcd`. -/
def Z13612_spec (m n : ℕ) : ℕ := Nat.gcd m n

-- The oracle agrees with the abstract `GCDMonoid` operation on ℕ (definitional `rfl`).
example (m n : ℕ) : Z13612_spec m n = gcd m n := (gcd_eq_nat_gcd m n).symm

-- Defining characterization: it is a common divisor and the greatest such.
example (m n : ℕ) : Z13612_spec m n ∣ m ∧ Z13612_spec m n ∣ n :=
  ⟨Nat.gcd_dvd_left m n, Nat.gcd_dvd_right m n⟩
example (m n c : ℕ) (hm : c ∣ m) (hn : c ∣ n) : c ∣ Z13612_spec m n :=
  Nat.dvd_gcd hm hn

-- Concrete kernel evaluation (decidable/computable):
example : Z13612_spec 12 18 = 6 := by decide
example : Z13612_spec 0 7 = 7 := by decide

/- ----- Z13660  (Q102761)  [wrong_target] ----- -/
/-- Wikifunctions Z13660 "least common multiple" — Wikidata Q102761.
    Signature: (Natural number, Natural number) → Natural number.
    Oracle: `Nat.lcm` (Lean core, computable on ℕ). The WikiLean primary_decl
    `GCDMonoid` (Mathlib.Algebra.GCDMonoid.Basic) is a TYPECLASS, not the
    operation — the faithful oracle is the concrete `Nat.lcm m n = m * n / Nat.gcd m n`. -/
def Z13660_spec (m n : ℕ) : ℕ := Nat.lcm m n

-- Defining relation: lcm via gcd (the usual "composite" implementation).
example (m n : ℕ) : Z13660_spec m n = m * n / Nat.gcd m n := by
  simp [Z13660_spec, Nat.lcm]

-- Concrete sanity check the kernel can decide.
example : Z13660_spec 4 6 = 12 := by decide

-- The GCD–LCM product law (Nat-specialized form of GCDMonoid.gcd_mul_lcm).
example (m n : ℕ) : Nat.gcd m n * Z13660_spec m n = m * n := by
  simp [Z13660_spec, Nat.gcd_mul_lcm]

/- ----- Z13667  (Q120976)  [faithful] ----- -/
/-- Wikifunctions Z13667 "factorial" — Wikidata Q120976.
    Oracle: `Nat.factorial` (computable ℕ → ℕ, kernel-decidable on concrete inputs).
    Defined by 0! = 1 and (n+1)! = (n+1) * n!. -/
def Z13667_spec (n : ℕ) : ℕ := Nat.factorial n

-- Recurrence the implementation must satisfy.
example : Z13667_spec 0 = 1 := by simp [Z13667_spec]
example (n : ℕ) : Z13667_spec (n + 1) = (n + 1) * Z13667_spec n := by
  simp [Z13667_spec, Nat.factorial_succ]

-- Concrete ground-truth checks (kernel-evaluable).
example : Z13667_spec 5 = 120 := by decide
example : Z13667_spec 0 = 1 := by decide
example : Z13667_spec 10 = 3628800 := by decide

-- Equivalent product characterization (Mathlib.Data.Nat.Factorial.BigOperators).
example (n : ℕ) : Z13667_spec n = ∏ i ∈ Finset.range n, (i + 1) := by
  simp only [Z13667_spec]; exact Nat.factorial_eq_prod_range_add_one n

/- ----- Z13701  (Q104752)  [faithful] ----- -/
/-- Wikifunctions Z13701 "are coprime (natural numbers)" — Wikidata Q104752.
    Oracle: `Nat.Coprime` (Lean core, `Init.Data.Nat.Coprime`), defined as
    `Nat.gcd m n = 1`; `[reducible]` so it is Decidable and kernel-evaluable.
    Note: WikiLean's primary_decl `IsCoprime` (Mathlib.RingTheory.Coprime.Basic)
    is the Bezout predicate `∃ a b, a*x+b*y=1` over a CommSemiring — correct concept
    but not directly computable; for ℕ it agrees with `Nat.Coprime` via
    `Nat.isCoprime_iff_coprime`. -/
def Z13701_spec (m n : ℕ) : Bool := decide (Nat.Coprime m n)

-- Oracle unfolds to the gcd test the implementations must satisfy.
example (m n : ℕ) : Z13701_spec m n = decide (Nat.gcd m n = 1) := by
  simp [Z13701_spec, Nat.Coprime]

-- Concrete sanity checks (kernel-decidable).
example : Z13701_spec 8 15 = true  := by decide   -- gcd 8 15 = 1
example : Z13701_spec 6 9  = false := by decide   -- gcd 6 9  = 3

-- Bridge to the ring-theoretic IsCoprime that WikiLean tagged (over ℤ):
example (m n : ℕ) : Z13701_spec m n = decide (IsCoprime (m : ℤ) n) := by
  simp [Z13701_spec, Nat.isCoprime_iff_coprime]

/- ----- Z13822  (Q2741788)  [faithful] ----- -/
/-- Wikifunctions Z13822 "modular multiplicative inverse" — Wikidata Q2741788.
    Oracle: `ZMod.inv` (Mathlib.Data.ZMod.Basic), accessed as `((a : ZMod n)⁻¹).val`,
    the canonical residue `0 ≤ r < n` with `a * r ≡ 1 (mod n)` when `Nat.Coprime a n`.
    Computable (extended Euclidean algorithm via `Nat.gcdA`/`Nat.xgcd`). -/
def Z13822_spec (a n : ℕ) : ℕ := ((a : ZMod n)⁻¹).val

/-- The returned value is a genuine inverse modulo `n` whenever `a` is coprime to `n`. -/
example (a n : ℕ) (h : Nat.Coprime a n) :
    (a : ZMod n) * (Z13822_spec a n : ZMod n) = 1 := by
  simpa [Z13822_spec] using ZMod.mul_val_inv (m := a) (n := n) h

/-- Sanity / decidability: for a positive modulus the residue is reduced. -/
example (a n : ℕ) (hn : 0 < n) : Z13822_spec a n < n := by
  haveI : NeZero n := ⟨hn.ne'⟩
  simpa [Z13822_spec] using ZMod.val_lt ((a : ZMod n)⁻¹)

-- Kernel-checkable example: 3⁻¹ mod 7 = 5  (since 3*5 = 15 ≡ 1 mod 7).
-- `decide` cannot reduce `ZMod.inv` (well-founded recursion via `Nat.gcdA`/`Nat.xgcd`),
-- so we pin the inverse by left-cancelling `3` against the two products that equal `1`.
example : Z13822_spec 3 7 = 5 := by
  show ((3 : ZMod 7)⁻¹).val = 5
  have h3 : (3 : ZMod 7) ≠ 0 := by decide
  have hgcd : (3 : ZMod 7) * (3 : ZMod 7)⁻¹ = 1 :=
    ZMod.coe_mul_inv_eq_one 3 (by decide)
  have h5 : (3 : ZMod 7) * 5 = 1 := by decide
  have hval : ((5 : ZMod 7)).val = 5 := by decide
  haveI : Fact (Nat.Prime 7) := ⟨by norm_num⟩
  have hinv : (3 : ZMod 7)⁻¹ = 5 := mul_left_cancel₀ h3 (by rw [hgcd, h5])
  rw [hinv, hval]

/- ----- Z13835  (Q23835349)  [faithful] ----- -/
/-- Wikifunctions Z13835 "nth Fibonacci number" — Wikidata Q23835349.
    Oracle: `Nat.fib : ℕ → ℕ` (computable, defined in Mathlib.Data.Nat.Fib.Basic).
    Convention `fib 0 = 0`, `fib 1 = 1`, recurrence `fib (n+2) = fib n + fib (n+1)`. -/
def Z13835_spec (n : ℕ) : ℕ := Nat.fib n

/-- Base cases agree with the oracle. -/
example : Z13835_spec 0 = 0 ∧ Z13835_spec 1 = 1 := ⟨rfl, rfl⟩

/-- The implementation must satisfy the defining Fibonacci recurrence. -/
example (n : ℕ) : Z13835_spec (n + 2) = Z13835_spec n + Z13835_spec (n + 1) := by
  simp [Z13835_spec, Nat.fib_add_two]

/-- Concrete sanity check (kernel-decidable). -/
example : Z13835_spec 10 = 55 := by decide

/- ----- Z13955  (Q190026)  [faithful] ----- -/
/-- Wikifunctions Z13955 "Euler totient function" — Wikidata Q190026.
    Oracle: `Nat.totient` (computable ℕ → ℕ), defined in Mathlib.Data.Nat.Totient
    as the number of naturals strictly less than `n` that are coprime to `n`. -/
def Z13955_spec (n : ℕ) : ℕ := Nat.totient n

-- Correspondence: the spec is exactly Mathlib's totient, i.e. the count of
-- coprime residues below n (the defining property the implementation must satisfy).
example (n : ℕ) :
    Z13955_spec n = ((Finset.range n).filter fun a => n.Coprime a).card := by
  rw [Z13955_spec, Nat.totient_eq_card_coprime]

-- Sanity checks the kernel can decide:
example : Z13955_spec 1 = 1 := by decide
example : Z13955_spec 6 = 2 := by decide
example : Z13955_spec 9 = 6 := by decide
-- For prime p, φ(p) = p - 1:
example {p : ℕ} (hp : p.Prime) : Z13955_spec p = p - 1 := Nat.totient_prime hp

/- ----- Z14933  (Q170043)  [faithful] ----- -/
/-- `Nat.Perfect` unfolds definitionally to a conjunction of decidable predicates,
    so it is decidable; Mathlib does not register this instance, so we provide it. -/
instance (n : ℕ) : Decidable (Nat.Perfect n) :=
  decidable_of_iff ((∑ i ∈ n.properDivisors, i = n) ∧ 0 < n) Iff.rfl

/-- Wikifunctions Z14933 "is perfect number" — Wikidata Q170043.
    Oracle: `Nat.Perfect` (Mathlib.NumberTheory.Divisors), a decidable `Prop` on ℕ.
    `Nat.Perfect n := (∑ i ∈ n.properDivisors, i = n) ∧ 0 < n`. -/
def Z14933_spec (n : ℕ) : Bool := decide (Nat.Perfect n)

-- Correspondence: matches "sum of proper divisors = n, and n positive".
example (n : ℕ) :
    Z14933_spec n = decide ((∑ i ∈ n.properDivisors, i = n) ∧ 0 < n) :=
  Bool.decide_congr Iff.rfl

-- Sanity: 6 = 1 + 2 + 3 is perfect; 8 is not.
example : Z14933_spec 6 = true := by decide
example : Z14933_spec 8 = false := by decide

-- Via the secondary characterization (for n > 0): perfect ⇔ σ-sum is 2n.
example {n : ℕ} (h : 0 < n) :
    Nat.Perfect n ↔ ∑ i ∈ n.divisors, i = 2 * n :=
  Nat.perfect_iff_sum_divisors_eq_two_mul h

/- ----- Z18194  (Q205170)  [representation_mismatch] ----- -/
/-- Wikifunctions Z18194 "powerset" — Wikidata Q205170.
    The WF takes a finite collection and returns the finite collection of all its sub-collections.
    primary_decl `Set.powerset` (Mathlib.Data.Set.Defs) is the faithful mathematical def but is
    noncomputable (returns `Set (Set α)`). The COMPUTABLE ground-truth oracle is `Finset.powerset`
    (Mathlib.Data.Finset.Powerset), which enumerates the subsets. -/
def Z18194_spec {α : Type*} [DecidableEq α] (s : Finset α) : Finset (Finset α) :=
  Finset.powerset s

-- Defining membership characterization: an element is in the result iff it is a subset.
example {α : Type*} [DecidableEq α] (s t : Finset α) :
    t ∈ Z18194_spec s ↔ t ⊆ s := by
  simp [Z18194_spec, Finset.mem_powerset]

-- Cardinality correspondence: |𝒫(s)| = 2 ^ |s| (machine-checkable on concrete inputs).
example {α : Type*} [DecidableEq α] (s : Finset α) :
    (Z18194_spec s).card = 2 ^ s.card := by
  simp [Z18194_spec, Finset.card_powerset]

-- Bridge to the primary_decl Set.powerset (the Set-valued, noncomputable mathematical def):
-- the coercion of the Finset oracle is the preimage of Set.powerset under the coercion.
example {α : Type*} [DecidableEq α] (s : Finset α) :
    ((Z18194_spec s : Finset (Finset α)) : Set (Finset α))
      = ((↑) : Finset α → Set α) ⁻¹' (s : Set α).powerset := by
  simp [Z18194_spec, Finset.coe_powerset]

-- Concrete kernel-decidable check, e.g. on {0,1} ⊆ ℕ:
example : (Z18194_spec ({0, 1} : Finset ℕ)).card = 4 := by decide

/- ----- Z13521  (Q32043)  [wrong_target] ----- -/
/-- Wikifunctions Z13521 "add two Natural numbers" — Wikidata Q32043.
    Oracle: natural-number addition `Nat.add` (= the `(+)` from the `AddCommMonoid ℕ`
    instance, whose `add` field is literally `Nat.add`). Computable on ℕ.
    NOTE: WikiLean primary_decl `AddCommMonoid` is the algebraic TYPECLASS
    (Mathlib.Algebra.Group.Defs), not the operation — corrected to `Nat.add`. -/
def Z13521_spec (a b : ℕ) : ℕ := a + b

-- The spec is exactly Lean-core `Nat.add` (the AddCommMonoid ℕ instance sets `add := Nat.add`).
example (a b : ℕ) : Z13521_spec a b = Nat.add a b := rfl

-- Concrete oracle check (kernel-decidable): the implementation must satisfy e.g.
example : Z13521_spec 17 25 = 42 := by decide

-- Sanity: agrees with the abstract AddCommMonoid `+` (HAdd on ℕ), as expected.
example (a b : ℕ) : Z13521_spec a b = HAdd.hAdd a b := rfl

/- ----- Z15483  (Q331350)  [wrong_target] ----- -/
/-- Wikifunctions Z15483 "nth r-simplex number" — Wikidata Q331350 (simplex / figurate number).
    The r-dimensional simplicial figurate numbers: the nth term of the r-simplex sequence is
    the binomial coefficient C(n + r - 1, r) = n(n+1)…(n+r-1) / r!.
      r = 1 → n (naturals); r = 2 → triangular numbers; r = 3 → tetrahedral numbers.
    Oracle: `Nat.choose (n + r - 1) r`, equivalently `Nat.multichoose n r`
    (Mathlib.Data.Nat.Choose.Basic). Both are computable on ℕ; the kernel decides equality.
    NOTE: the WikiLean tag `Affine.Simplex` is a *geometric* structure, unrelated — wrong_target. -/
def Z15483_spec (n r : ℕ) : ℕ := Nat.choose (n + r - 1) r

-- Correspondence with the stars-and-bars / multichoose form (proved in Mathlib).
example (n r : ℕ) : Z15483_spec n r = Nat.multichoose n r := by
  simp [Z15483_spec, Nat.multichoose_eq]

-- Sanity checks: triangular numbers (r = 2) and tetrahedral numbers (r = 3).
example : Z15483_spec 4 2 = 10 := by decide   -- 1,3,6,10,…
example : Z15483_spec 4 3 = 20 := by decide   -- 1,4,10,20,…
example : Z15483_spec 5 1 = 5  := by decide   -- r = 1 ↦ the naturals

/- ----- Z15849  (Q192826)  [faithful] ----- -/
/-- Wikifunctions Z15849 "Kronecker delta" — Wikidata Q192826.
    Signature: (ℕ, ℕ) → ℕ,  δ(i,j) = if i = j then 1 else 0.
    Mathlib has no standalone Kronecker-delta def; the concept is the entries of the
    identity matrix, characterized by `Matrix.one_apply`
    (Mathlib.Data.Matrix.Diagonal): `(1 : Matrix n n α) i j = if i = j then 1 else 0`.
    Computable oracle over ℕ (DecidableEq ℕ ⇒ kernel-decidable). -/
def Z15849_spec (i j : ℕ) : ℕ := if i = j then 1 else 0

-- The spec is exactly the (ℕ,ℕ) entry of the natural-number identity matrix:
open Matrix in
example (i j : ℕ) : Z15849_spec i j = (1 : Matrix ℕ ℕ ℕ) i j := by
  rw [Matrix.one_apply, Z15849_spec]   -- both sides: if i = j then 1 else 0

-- Concrete kernel checks:
example : Z15849_spec 3 3 = 1 := rfl
example : Z15849_spec 2 5 = 0 := rfl

/- ----- Z20000  (Q182505)  [representation_mismatch] ----- -/
/-- Wikifunctions Z20000 "Bayes' theorem conditional probability P(A|B)" — Wikidata Q182505.
    Inputs (ℚ): likelihood P(B|A) = `pBA`, prior P(A) = `pA`, evidence P(B) = `pB`.
    Returns the posterior P(A|B) = P(B|A)·P(A)/P(B).

    Mathlib's `ProbabilityTheory.cond_eq_inv_mul_cond_mul`
    (Mathlib.Probability.ConditionalProbability) states the abstract measure-theoretic
    form `μ[t | s] = (μ s)⁻¹ * μ[s | t] * μ t` over ℝ≥0∞, which is noncomputable.
    This spec is the faithful computable ℚ-arithmetic oracle mirroring that identity
    with `μ s ↦ pB`, `μ[s | t] ↦ pBA`, `μ t ↦ pA`. -/
def Z20000_spec (pBA pA pB : ℚ) : ℚ := pBA * pA / pB

/-- Correspondence: the spec equals the (μ s)⁻¹ * μ[s|t] * μ t arithmetic shape of Bayes'
    theorem, instantiated over ℚ (with pB ↠ μ s, pBA ↠ μ[s|t], pA ↠ μ t). -/
example (pBA pA pB : ℚ) : Z20000_spec pBA pA pB = pB⁻¹ * pBA * pA := by
  simp only [Z20000_spec]
  ring

-- concrete check (the classic medical-test style numbers):
-- P(B|A)=9/10, P(A)=1/100, P(B)=27/250  ⇒  P(A|B) = (9/10)(1/100)/(27/250) = 1/12
example : Z20000_spec (9/10) (1/100) (27/250) = 1/12 := by
  simp only [Z20000_spec]
  norm_num

/- ----- Z28925  (Q208225)  [faithful] ----- -/
/-- Wikifunctions Z28925 "is Pythagorean triple" — Wikidata Q208225.
    Oracle: `Mathlib.NumberTheory.PythagoreanTriples.PythagoreanTriple` (a decidable Prop;
    Mathlib defines it over ℤ as `x*x + y*y = z*z`). The WF takes (ℕ,ℕ,ℕ)→Bool,
    so we phrase the ℕ oracle and bridge to the Mathlib ℤ predicate via casts. -/
def Z28925_spec (a b c : ℕ) : Bool := decide (a * a + b * b = c * c)

-- The ℕ oracle returns `true` exactly when Mathlib's `PythagoreanTriple` holds over ℤ
-- on the natural inputs (cast to integers).
example (a b c : ℕ) :
    Z28925_spec a b c = true ↔ PythagoreanTriple (a : ℤ) (b : ℤ) (c : ℤ) := by
  unfold Z28925_spec PythagoreanTriple
  rw [decide_eq_true_eq]
  constructor
  · intro h; exact_mod_cast congrArg (Nat.cast : ℕ → ℤ) h
  · intro h; exact_mod_cast h

-- Concrete sanity checks (kernel-decidable):
example : Z28925_spec 3 4 5 = true  := by decide
example : Z28925_spec 6 8 10 = true := by decide
example : Z28925_spec 1 2 3 = false := by decide

/- ======================================================================== -/
/- TIER 2 — oracle_testable (computable ℚ/ℤ + Float oracles; differential-test ground truth) -/
/- ======================================================================== -/

/- ----- Z30840  (Q19033)  [wrong_target] ----- -/
/- Wikifunctions Z30840 "arithmetic mean of Natural numbers as Rational" — Wikidata Q19033.
    The function takes a finite collection of natural numbers and returns their arithmetic
    mean exactly as a Rational number: (a₁ + ⋯ + aₙ) / n.

    NOTE on primary_decl: `MeasureTheory.average` (Mathlib.MeasureTheory.Integral.Average)
    is the NONCOMPUTABLE Bochner integral average of a function over a measure — a
    wrong_target for this elementary list→ℚ mean. The faithful oracle is built from the
    computable primitives `List.sum` (cast to ℚ) and division in ℚ; it is fully computable.
    The empty-list convention here returns 0 (matching `x / 0 = 0` in ℚ); a real
    implementation may instead reject the empty input. -/
namespace Z30840

/-- Oracle: arithmetic mean of a list of naturals, as a rational. Computable over ℚ. -/
def spec (l : List ℕ) : ℚ :=
  ((l.map (Nat.cast : ℕ → ℚ)).sum) / (l.length : ℚ)

/-- Concrete sanity check: mean of [1,2,3,4] = 10/4 = 5/2. -/
example : Z30840.spec [1, 2, 3, 4] = 5 / 2 := by
  simp only [Z30840.spec, List.map_cons, List.map_nil, List.sum_cons, List.sum_nil,
    List.length_cons, List.length_nil]
  norm_num

/-- Singleton: the mean of [a] is a. -/
example (a : ℕ) : Z30840.spec [a] = (a : ℚ) := by
  simp [Z30840.spec]

/-- Correspondence with the defining identity: mean * n = sum (for nonempty lists). -/
example (l : List ℕ) (hl : l ≠ []) :
    Z30840.spec l * (l.length : ℚ) = (l.map (Nat.cast : ℕ → ℚ)).sum := by
  have hlen : (l.length : ℚ) ≠ 0 := by
    exact_mod_cast (List.length_pos_iff.mpr hl).ne'
  rw [Z30840.spec, div_mul_cancel₀ _ hlen]

/-- A variant expressing the numerator via the natural-number sum cast once:
    `Nat.cast_list_sum` rewrites `(↑l.sum) = (l.map (↑)).sum`. -/
example (l : List ℕ) :
    Z30840.spec l = (l.sum : ℚ) / (l.length : ℚ) := by
  rw [Z30840.spec, Nat.cast_list_sum]

end Z30840

/- ----- Z10862  (Q40276)  [wrong_target] ----- -/
/-- Wikifunctions Z10862 "(!) multiply two numeric strings (full stop input/output format)"
    — Wikidata Q40276.
    The WF takes two decimal-digit strings and returns their product as a decimal string.
    primary_decl "Mul" is the multiplication TYPECLASS (Lean core), not an oracle and not in
    the cited module; the computable oracle is concrete `*` on ℕ/ℤ (and ℚ for the "full stop"
    decimal variant). The WF must parse strings, multiply, and re-render. -/

-- Integer oracle (computable, decidable on concrete inputs):
def Z10862_spec (a b : ℤ) : ℤ := a * b

-- Correspondence the implementation must satisfy after parse/render:
--   parse (Z10862_impl (render a) (render b)) = a * b
-- e.g. on naturals it agrees with core Nat.mul:
example (m n : ℕ) : (Z10862_spec (m : ℤ) (n : ℤ)) = ((m * n : ℕ) : ℤ) := by
  unfold Z10862_spec; push_cast; ring

-- Decimal "full stop" variant — oracle over ℚ (still computable on concrete literals):
def Z10862_spec_rat (a b : ℚ) : ℚ := a * b
example : Z10862_spec_rat (3/2) (4) = 6 := by norm_num [Z10862_spec_rat]
example : Z10862_spec 12 34 = 408 := by decide

/- ----- Z21917  (Q381040)  [representation_mismatch] ----- -/
/-- Wikifunctions Z21917 "complex conjugate (integer list)" — Wikidata Q381040.
    The WF encodes a complex number as a pair/list of two integers (a, b) = a + b·i
    and returns its conjugate (a, -b). Mathlib's canonical operation is
    `starRingEnd ℂ` (notation `conj`), defined via `Complex.instStarRing`
    as `star z = ⟨z.re, -z.im⟩` (Mathlib.Data.Complex.Basic), where
    `starRingEnd : R →+* R` lives in Mathlib.Algebra.Star.Basic.
    starRingEnd ℂ is noncomputable (over ℝ); the WF's integer-pair form is computable. -/
def Z21917_spec (p : ℤ × ℤ) : ℤ × ℤ := (p.1, -p.2)

-- Correspondence: the integer-pair oracle matches Mathlib `conj` on the embedded complex number.
example (a b : ℤ) :
    (starRingEnd ℂ) (a + b * Complex.I) =
      ((Z21917_spec (a, b)).1 : ℂ) + ((Z21917_spec (a, b)).2 : ℂ) * Complex.I := by
  simp [Z21917_spec, map_add, map_mul, map_intCast, Complex.conj_I]

-- Componentwise sanity check (purely on ℤ, decidable/computable):
example : Z21917_spec (3, -5) = (3, 5) := by decide

/- ----- Z31173  (Q852973)  [wrong_target] ----- -/
/-- Wikifunctions Z31173 "Euler characteristic of polyhedron" — Wikidata Q852973
    ("Euler's polyhedron theorem"). Signature (ℕ, ℕ, ℕ) → ℤ: given the number of
    vertices V, edges E, and faces F of a polyhedron, returns the Euler characteristic
    χ = V − E + F.

    NOTE: WikiLean's primary_decl `HomologicalComplex.eulerChar`
    (Mathlib.Algebra.Homology.EulerCharacteristic) EXISTS but is the WRONG target —
    it is the abstract homological-algebra Euler characteristic (a noncomputable
    alternating-sign finsum of `Module.finrank` over a chain complex), not the
    elementary V−E+F formula. Mathlib has no declaration for the polyhedron Euler
    characteristic (Q852973 is listed unformalized in docs/1000.yaml, no `decls`),
    so the oracle is the arithmetic expression itself; it is computable in ℕ→ℤ. -/
def Z31173_spec (V E F : ℕ) : ℤ := (V : ℤ) - (E : ℤ) + (F : ℤ)

/-- The oracle is exactly V − E + F. -/
example (V E F : ℕ) : Z31173_spec V E F = (V : ℤ) - E + F := rfl

/-- Euler's polyhedron theorem (the *content* WF Z31173 alludes to): for a convex
    (more generally, simply-connected / genus-0) polyhedron, χ = 2. This is NOT
    formalized in Mathlib; stated here only as the specification the values satisfy. -/
example : Z31173_spec 8 12 6 = 2 := rfl   -- cube: V=8, E=12, F=6 ⇒ χ = 2
example : Z31173_spec 4 6 4 = 2 := rfl    -- tetrahedron: V=4, E=6, F=4 ⇒ χ = 2

/- ----- Z21003  (Q204037)  [faithful] ----- -/
/-- Wikifunctions Z21003 "natural logarithm (float64)" — Wikidata Q204037.
    The WF is an IEEE-754 binary64 routine, so the OPERATIONAL oracle is Lean's
    `Float.log` (also binary64, `@[extern]` to libm): directly `#eval`-comparable
    to the live function — bit-for-bit on a shared libm, within ~1 ULP across libms.
    The mathematical IDEAL it approximates is `Real.log` (noncomputable). -/
def Z21003_spec : Float → Float := Float.log

-- Operational sanity (native eval; this is what a differential test checks):
#guard Float.abs (Z21003_spec 1.0 - 0.0) < 1e-9
#guard Float.abs (Z21003_spec (Float.exp 1.0) - 1.0) < 1e-9

/-- Mathematical ideal: the real natural logarithm the float impl approximates.
    (Mathlib's own `@[wikidata]` tag on `Real.log` is Q11197.) -/
noncomputable def Z21003_ideal : ℝ → ℝ := Real.log

-- Defining property on the natural-log domain x > 0: it inverts exp.
example {x : ℝ} (hx : 0 < x) : Real.exp (Z21003_ideal x) = x := by
  simpa [Z21003_ideal] using Real.exp_log hx

example (x : ℝ) : Z21003_ideal (Real.exp x) = x := by
  simp only [Z21003_ideal]; exact Real.log_exp x

-- Multiplicativity (functional equation).
example {x y : ℝ} (hx : x ≠ 0) (hy : y ≠ 0) :
    Z21003_ideal (x * y) = Z21003_ideal x + Z21003_ideal y := by
  simp only [Z21003_ideal]; exact Real.log_mul hx hy

/- ----- Z21005  (Q966582)  [faithful] ----- -/
/-- Wikifunctions Z21005 "float64 logarithm base 10" — Wikidata Q966582.
    OPERATIONAL oracle: IEEE-754 binary64 `Float.log x / Float.log 10` (Lean has no
    primitive `log10`; libm-faithful and `#eval`-comparable to the live function).
    Mathematical IDEAL: `Real.logb 10` (noncomputable). -/
def Z21005_spec : Float → Float := fun x => Float.log x / Float.log 10.0

-- Operational sanity (native eval):
#guard Float.abs (Z21005_spec 1000.0 - 3.0) < 1e-9
#guard Float.abs (Z21005_spec 1.0 - 0.0) < 1e-9

/-- Mathematical ideal: the real base-10 logarithm the float impl approximates. -/
noncomputable def Z21005_ideal : ℝ → ℝ := Real.logb 10

-- Defining equation: base-10 log equals log x / log 10.
example (x : ℝ) : Z21005_ideal x = Real.log x / Real.log 10 := by
  simp [Z21005_ideal, Real.logb]

-- Characterizing inverse property: logb 10 (10 ^ x) = x.
example (x : ℝ) : Z21005_ideal ((10 : ℝ) ^ x) = x := by
  simp [Z21005_ideal, Real.logb_rpow (b := (10 : ℝ)) (b_pos := by norm_num)
    (b_ne_one := by norm_num)]

/- ----- Z12665  (Q33456)  [faithful] ----- -/
/-- Wikifunctions Z12665 "exponentiation" — Wikidata Q33456.
    Signature (float64, float64) -> float64, i.e. real base ^ real exponent.
    OPERATIONAL oracle: IEEE-754 binary64 `Float` power `x ^ y` (`@[extern]` to
    libm `pow`), directly `#eval`-comparable to the live function.
    Mathematical IDEAL: `Real.rpow` (noncomputable; `x ^ y = ((x:ℂ)^(y:ℂ)).re`).

    Note: WikiLean's primary_decl `Monoid.npow` is WRONG_TARGET — a `class Monoid`
    field of type `ℕ → M → M` (NATURAL-number exponent), not real^real. -/
def Z12665_spec : Float → Float → Float := fun x y => x ^ y

-- Operational sanity (native eval):
#guard Float.abs (Z12665_spec 8.0 2.0 - 64.0) < 1e-9
#guard Float.abs (Z12665_spec 9.0 0.5 - 3.0) < 1e-9

/-- Mathematical ideal: real exponentiation the float impl approximates. -/
noncomputable def Z12665_ideal : ℝ → ℝ → ℝ := Real.rpow

-- Correspondence: the ideal is exactly the `HPow ℝ ℝ ℝ` notation `x ^ y`.
example (x y : ℝ) : Z12665_ideal x y = x ^ y := Real.rpow_eq_pow x y

-- For x > 0, exponentiation = exp (log x · y).
example (x y : ℝ) (hx : 0 < x) : Z12665_ideal x y = Real.exp (Real.log x * y) := by
  simpa [Z12665_ideal, Real.rpow_eq_pow] using Real.rpow_def_of_pos hx y

-- For a NATURAL exponent the ideal collapses to the (mis-targeted) npow case.
example (x : ℝ) (n : ℕ) : Z12665_ideal x (n : ℝ) = x ^ n := by
  simp [Z12665_ideal, Real.rpow_eq_pow, Real.rpow_natCast x n]

/- ----- Z13341  (Q2266329)  [faithful] ----- -/
/-- Wikifunctions Z13341 "linear interpolation" — Wikidata Q2266329.
    Signature (float64, float64, float64) → float64, lerp(a,b,t) = (1-t)*a + t*b.
    OPERATIONAL oracle: the IEEE-754 binary64 arithmetic itself (no transcendental
    call), so `#eval`-exact against the live function on representable inputs.
    Mathematical IDEAL: `AffineMap.lineMap` over ℝ. -/
def Z13341_spec (a b t : Float) : Float := (1.0 - t) * a + t * b

-- Operational sanity (native eval; exact on binary-representable inputs):
#guard Z13341_spec 10.0 20.0 0.25 == 12.5
#guard Z13341_spec 10.0 20.0 0.0 == 10.0
#guard Z13341_spec 10.0 20.0 1.0 == 20.0

/-- Mathematical ideal: exact affine interpolation over ℝ. -/
noncomputable def Z13341_ideal (a b t : ℝ) : ℝ := AffineMap.lineMap a b t

/-- Correspondence: the ideal equals the closed-form formula. -/
example (a b t : ℝ) : Z13341_ideal a b t = (1 - t) * a + t * b := by
  simp [Z13341_ideal, AffineMap.lineMap_apply_ring]

/-- Equivalently in the `t*(b - a) + a` form. -/
example (a b t : ℝ) : Z13341_ideal a b t = t * (b - a) + a :=
  AffineMap.lineMap_apply_ring' a b t

/-- Boundary conditions characterizing linear interpolation. -/
example (a b : ℝ) : Z13341_ideal a b 0 = a := by
  simp [Z13341_ideal, AffineMap.lineMap_apply_zero]
example (a b : ℝ) : Z13341_ideal a b 1 = b := by
  simp [Z13341_ideal, AffineMap.lineMap_apply_one]

/- ----- Z35278  (Q204570)  [faithful] ----- -/
/- Wikifunctions Z35278 "Shannon entropy from string" — Wikidata Q204570.
   Signature: (String) → float64.

   Shannon entropy of a string `s` is `H(s) = - ∑_c p_c · log_b p_c`, summed over
   distinct characters `c`, with `p_c = (count of c in s) / |s|` and base `b = 2`
   (bits — the conventional "entropy from string" return).

   OPERATIONAL oracle: assembled over IEEE-754 binary64 `Float`, so it is
   `#eval`-comparable to the live function. Mathematical IDEAL: the same sum over
   ℝ using Mathlib's per-term `Real.negMulLog x = -x * log x` (nats) — Mathlib has
   no string/distribution-level Shannon entropy, so the oracle is assembled. -/
namespace Z35278

/-- Distinct characters of a string. -/
def chars (s : String) : List Char := s.toList.dedup

/-- Empirical probability of character `c` in string `s` (Float). -/
def probF (s : String) (c : Char) : Float :=
  (s.toList.count c).toFloat / s.toList.length.toFloat

/-- OPERATIONAL oracle: Shannon entropy in BITS over Float (what the WF returns).
    The `p == 0` guard encodes the `0·log 0 = 0` convention. -/
def Z35278_spec (s : String) : Float :=
  (chars s).foldr
    (fun c acc =>
      let p := probF s c
      (if p == 0.0 then 0.0 else -p * (Float.log p / Float.log 2.0)) + acc) 0.0

-- Operational sanity (native eval):
#guard Float.abs (Z35278_spec "AB" - 1.0) < 1e-9      -- two equiprobable symbols → 1 bit
#guard Float.abs (Z35278_spec "AAAA" - 0.0) < 1e-9    -- one symbol → 0 bits

/-- Empirical probability of character `c` in string `s` (ℝ, for the ideal). -/
noncomputable def prob (s : String) (c : Char) : ℝ :=
  (s.toList.count c : ℝ) / (s.toList.length : ℝ)

/-- Mathematical ideal in NATS: the sum of Mathlib's `Real.negMulLog` over the
    empirical char distribution. -/
noncomputable def entropyNats (s : String) : ℝ :=
  (chars s).foldr (fun c acc => Real.negMulLog (prob s c) + acc) 0

/-- Mathematical ideal in BITS (matching the Float oracle's convention). -/
noncomputable def entropyBits (s : String) : ℝ :=
  (chars s).foldr (fun c acc => -(prob s c) * Real.logb 2 (prob s c) + acc) 0

/-- Bits and nats ideals differ only by the base-conversion factor `log 2`. This
    pins the WF's bits value to the Mathlib `negMulLog`-based nats value. -/
example (s : String) : entropyBits s = entropyNats s / Real.log 2 := by
  unfold entropyBits entropyNats
  induction chars s with
  | nil => simp
  | cons c cs ih =>
    rw [List.foldr_cons, List.foldr_cons, ih, add_div]
    congr 1
    rw [Real.negMulLog, Real.logb]
    ring

end Z35278

/- ======================================================================== -/
/- TIER 3 — spec_only (noncomputable real oracle only)                      -/
/- ======================================================================== -/

/- ----- Z16483  (Q190573)  [representation_mismatch] ----- -/
/-- Wikifunctions Z16483 "(!) gamma function (strings)" — Wikidata Q190573.
    The Γ (Gamma) function. Wikifunctions signature is (String) -> String, a decimal-string
    encoding of a real-valued transcendental function (the "(!)" flags this representation issue).
    Oracle: `Real.Gamma : ℝ → ℝ`, defined as `(Complex.Gamma s).re`.
    NONCOMPUTABLE: Complex.Gamma is built on the Bochner integral (Complex.GammaIntegral /
    GammaAux), so the Lean kernel cannot evaluate it for concrete inputs — this is a spec only.
    primary_decl `Complex.Gamma` exists verbatim at
    Mathlib/Analysis/SpecialFunctions/Gamma/Basic.lean:287 inside `namespace Complex`. -/
noncomputable def Z16483_spec : ℝ → ℝ := Real.Gamma

/-- Real.Gamma is the real part of Complex.Gamma (definitional bridge to the primary_decl). -/
example (s : ℝ) : Z16483_spec s = (Complex.Gamma (s : ℂ)).re := rfl

/-- Correspondence the implementation must satisfy: Γ(n+1) = n! for natural n
    (`Real.Gamma_nat_eq_factorial`), pinning the oracle's values on the integers. -/
example (n : ℕ) : Z16483_spec (n + 1) = (n.factorial : ℝ) := Real.Gamma_nat_eq_factorial n

/-- Functional equation Γ(s+1) = s·Γ(s) (`Real.Gamma_add_one`), s ≠ 0. -/
example {s : ℝ} (hs : s ≠ 0) : Z16483_spec (s + 1) = s * Z16483_spec s :=
  Real.Gamma_add_one hs

