#!/usr/bin/env python3
"""A type compiler: Wikifunctions type definition -> Lean, on the `Model.ZObject` substrate.

The goal of the ground-up rebuild is to *generate* the per-type Lean rather than hand-write it.
The authoritative definition of a type is either:

  * a built-in type -> the function-schemata `data/CANONICAL/<ZID>.yaml` JSON-Schema
    (`<ZID>_literal.properties` lists the keys), or
  * a community type -> its live `Z4` definition via `wikilambda_fetch`
    (`Z2K2.Z4K2` lists the keys as `Z3` objects).

Both reduce to the same shape: a type ZID plus its ordered data keys (everything but `Z1K1`).
From that we emit, for `Zxx`: a normal-form smart constructor `Zxx.mk`, one accessor per key,
and a well-formedness recognizer `isZxx` (right type tag + all declared keys present) — all in
terms of the hand-written `ZObject` primitives.

Only a handful of types are hand-written (`Z1`/ZObject itself and the `Z6`/`Z9` terminals it
bottoms out in); everything else is generated by this tool.

Usage:  python3 codegen/gen_type.py Z40 Z17 Z19677
"""
from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "Wikifunctions" / "Model" / "Types"
SCHEMA_RAW = ("https://gitlab.wikimedia.org/repos/abstract-wiki/wikifunctions/"
              "function-schemata/-/raw/main/data/CANONICAL/{}.yaml")
API = "https://www.wikifunctions.org/w/api.php"


def _curl(url: str) -> str:
    return subprocess.run(["curl", "-sS", "--max-time", "40", url],
                          capture_output=True, text=True).stdout


def from_schema(zid: str):
    """(label, [keyids], source) from the function-schemata YAML, or None if absent."""
    txt = _curl(SCHEMA_RAW.format(zid))
    if not txt.strip() or "definitions" not in txt:
        return None
    m = re.match(rf"#\s*{zid}/(\S+)", txt)          # leading comment "# Z40/Boolean (Z4/Type)"
    label = m.group(1) if m else zid
    lit = (yaml.safe_load(txt).get("definitions", {}).get("objects", {}) or {}).get(f"{zid}_literal")
    if not lit or "properties" not in lit:
        return None
    keys = [k for k in lit["properties"].keys() if k != "Z1K1"]
    return label, keys, f"function-schemata {zid}.yaml"


def from_live(zid: str):
    """(label, [keyids], source) from the live Z4 definition (for community types)."""
    out = _curl(f"{API}?action=wikilambda_fetch&format=json&zids={zid}")
    if not out.strip():
        return None
    obj = json.loads(json.loads(out)[zid]["wikilambda_fetch"])
    z4 = obj.get("Z2K2", {})
    keys = [k["Z3K2"] for k in z4.get("Z4K2", []) if isinstance(k, dict) and k.get("Z3K2")]
    label = zid
    try:
        lbls = obj["Z2K3"]["Z12K1"]
        label = next((m["Z11K2"] for m in lbls if isinstance(m, dict) and m.get("Z11K1") == "Z1002"), zid)
    except Exception:
        pass
    return label, keys, "live Z4 (wikilambda_fetch)"


def type_spec(zid: str):
    return from_schema(zid) or from_live(zid)


def emit(zid: str, label: str, keys: list[str], source: str) -> str:
    arg = lambda k: k.lower()
    ctor_args = "".join(f" ({arg(k)} : ZObject)" for k in keys)
    entries = ", ".join([f'("Z1K1", reference "{zid}")'] + [f'("{k}", {arg(k)})' for k in keys])
    accessors = "\n\n".join(
        f'/-- Accessor for key `{k}`. -/\ndef {zid}.{k}? (z : ZObject) : Option ZObject := z.get? "{k}"'
        for k in keys) or "-- (no data keys)"
    checks = " &&\n  ".join([f'z.typeId? == some "{zid}"'] + [f'(z.get? "{k}").isSome' for k in keys])
    mk_call = f"{zid}.mk" + "".join(' (reference "Z1")' for _ in keys)
    return f'''import Wikifunctions.Model.ZObject

/-! # `{zid}`/{label} — AUTO-GENERATED, do not edit

Generated by `codegen/gen_type.py` from {source}. Regenerate with
`python3 codegen/gen_type.py {zid}`. Built on the hand-written `Model.ZObject` substrate. -/

namespace Wikifunctions.Model
open ZObject

/-- `{zid}`/{label} smart constructor: the normal-form ZObject with tag `{zid}`. -/
def {zid}.mk{ctor_args} : ZObject :=
  node [{entries}]

{accessors}

/-- `z` is a `{zid}`/{label}: correct `Z1K1` type tag and every declared key present. -/
def is{zid} (z : ZObject) : Bool :=
  {checks}

/-- Self-check: the generated constructor produces a value the recognizer accepts. -/
example : is{zid} ({mk_call}) = true := by decide

end Wikifunctions.Model
'''


def main(argv: list[str]) -> int:
    if not argv:
        print("usage: gen_type.py <ZID> [<ZID> ...]", file=sys.stderr)
        return 2
    OUT.mkdir(parents=True, exist_ok=True)
    rc = 0
    for zid in argv:
        s = type_spec(zid)
        if not s:
            print(f"{zid}: no function-schemata YAML and no live Z4 — skipped", file=sys.stderr)
            rc = 1
            continue
        label, keys, source = s
        (OUT / f"{zid}.lean").write_text(emit(zid, label, keys, source))
        print(f"{zid}/{label}: keys {keys or '[]'}  <- {source}  ->  Wikifunctions/Model/Types/{zid}.lean")
    return rc


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
