import Wikifunctions.Model.ZObject

/-! # `Z11`/Monolingual — AUTO-GENERATED, do not edit

Generated by `codegen/gen_type.py` from function-schemata Z11.yaml. Regenerate with
`python3 codegen/gen_type.py Z11`. Built on the hand-written `Model.ZObject` substrate. -/

namespace Wikifunctions.Model
open ZObject

/-- `Z11`/Monolingual smart constructor: the canonical-form ZObject whose `Z1K1` tag is `ref "Z11"`. -/
def Z11.mk (z11k1 : ZObject) (z11k2 : ZObject) : ZObject :=
  node [("Z1K1", ref "Z11"), ("Z11K1", z11k1), ("Z11K2", z11k2)]

/-- Accessor for key `Z11K1`. -/
def Z11.Z11K1? (z : ZObject) : Option ZObject := z.get? "Z11K1"

/-- Accessor for key `Z11K2`. -/
def Z11.Z11K2? (z : ZObject) : Option ZObject := z.get? "Z11K2"

/-- `z` is a `Z11`/Monolingual: correct `Z1K1` type tag and every declared key present. -/
def isZ11 (z : ZObject) : Bool :=
  z.typeId? == some "Z11" &&
  (z.get? "Z11K1").isSome &&
  (z.get? "Z11K2").isSome

/-- Self-check: the generated constructor produces a value the recognizer accepts. -/
example : isZ11 (Z11.mk (ref "Z1") (ref "Z1")) = true := by decide

end Wikifunctions.Model
