import Wikifunctions.Model.ZObject

/-! # `Z12`/Multilingual — AUTO-GENERATED, do not edit

Generated by `codegen/gen_type.py` from function-schemata Z12.yaml. Regenerate with
`python3 codegen/gen_type.py Z12`. Built on the hand-written `Model.ZObject` substrate. -/

namespace Wikifunctions.Model
open ZObject

/-- `Z12`/Multilingual smart constructor: the normal-form ZObject with tag `Z12`. -/
def Z12.mk (z12k1 : ZObject) : ZObject :=
  node [("Z1K1", reference "Z12"), ("Z12K1", z12k1)]

/-- Accessor for key `Z12K1`. -/
def Z12.Z12K1? (z : ZObject) : Option ZObject := z.get? "Z12K1"

/-- `z` is a `Z12`/Multilingual: correct `Z1K1` type tag and every declared key present. -/
def isZ12 (z : ZObject) : Bool :=
  z.typeId? == some "Z12" &&
  (z.get? "Z12K1").isSome

/-- Self-check: the generated constructor produces a value the recognizer accepts. -/
example : isZ12 (Z12.mk (reference "Z1")) = true := by decide

end Wikifunctions.Model
