import Wikifunctions.Model.ZObject

/-! # `Z14`/Implementation — AUTO-GENERATED, do not edit

Generated by `codegen/gen_type.py` from function-schemata Z14.yaml. Regenerate with
`python3 codegen/gen_type.py Z14`. Built on the hand-written `Model.ZObject` substrate. -/

namespace Wikifunctions.Model
open ZObject

/-- `Z14`/Implementation smart constructor: the normal-form ZObject whose `Z1K1` tag is `reference "Z14"`. -/
def Z14.mk (z14k1 : ZObject) (z14k2 : ZObject) (z14k3 : ZObject) (z14k4 : ZObject) : ZObject :=
  node [("Z1K1", reference "Z14"), ("Z14K1", z14k1), ("Z14K2", z14k2), ("Z14K3", z14k3), ("Z14K4", z14k4)]

/-- Accessor for key `Z14K1`. -/
def Z14.Z14K1? (z : ZObject) : Option ZObject := z.get? "Z14K1"

/-- Accessor for key `Z14K2`. -/
def Z14.Z14K2? (z : ZObject) : Option ZObject := z.get? "Z14K2"

/-- Accessor for key `Z14K3`. -/
def Z14.Z14K3? (z : ZObject) : Option ZObject := z.get? "Z14K3"

/-- Accessor for key `Z14K4`. -/
def Z14.Z14K4? (z : ZObject) : Option ZObject := z.get? "Z14K4"

/-- `z` is a `Z14`/Implementation: correct `Z1K1` type tag and every declared key present. -/
def isZ14 (z : ZObject) : Bool :=
  z.typeId? == some "Z14" &&
  (z.get? "Z14K1").isSome &&
  (z.get? "Z14K2").isSome &&
  (z.get? "Z14K3").isSome &&
  (z.get? "Z14K4").isSome

/-- Self-check: the generated constructor produces a value the recognizer accepts. -/
example : isZ14 (Z14.mk (reference "Z1") (reference "Z1") (reference "Z1") (reference "Z1")) = true := by decide

end Wikifunctions.Model
