import Wikifunctions.Model.ZObject

/-! # `Z16`/Code — AUTO-GENERATED, do not edit

Generated by `codegen/gen_type.py` from function-schemata Z16.yaml. Regenerate with
`python3 codegen/gen_type.py Z16`. Built on the hand-written `Model.ZObject` substrate. -/

namespace Wikifunctions.Model
open ZObject

/-- `Z16`/Code smart constructor: the normal-form ZObject with tag `Z16`. -/
def Z16.mk (z16k1 : ZObject) (z16k2 : ZObject) : ZObject :=
  node [("Z1K1", reference "Z16"), ("Z16K1", z16k1), ("Z16K2", z16k2)]

/-- Accessor for key `Z16K1`. -/
def Z16.Z16K1? (z : ZObject) : Option ZObject := z.get? "Z16K1"

/-- Accessor for key `Z16K2`. -/
def Z16.Z16K2? (z : ZObject) : Option ZObject := z.get? "Z16K2"

/-- `z` is a `Z16`/Code: correct `Z1K1` type tag and every declared key present. -/
def isZ16 (z : ZObject) : Bool :=
  z.typeId? == some "Z16" &&
  (z.get? "Z16K1").isSome &&
  (z.get? "Z16K2").isSome

/-- Self-check: the generated constructor produces a value the recognizer accepts. -/
example : isZ16 (Z16.mk (reference "Z1") (reference "Z1")) = true := by decide

end Wikifunctions.Model
