import Wikifunctions.Model.ZObject

/-! # `Z17`/Argument — AUTO-GENERATED, do not edit

Generated by `codegen/gen_type.py` from function-schemata Z17.yaml. Regenerate with
`python3 codegen/gen_type.py Z17`. Built on the hand-written `Model.ZObject` substrate. -/

namespace Wikifunctions.Model
open ZObject

/-- `Z17`/Argument smart constructor: the normal-form ZObject whose `Z1K1` tag is `reference "Z17"`. -/
def Z17.mk (z17k1 : ZObject) (z17k2 : ZObject) (z17k3 : ZObject) : ZObject :=
  node [("Z1K1", reference "Z17"), ("Z17K1", z17k1), ("Z17K2", z17k2), ("Z17K3", z17k3)]

/-- Accessor for key `Z17K1`. -/
def Z17.Z17K1? (z : ZObject) : Option ZObject := z.get? "Z17K1"

/-- Accessor for key `Z17K2`. -/
def Z17.Z17K2? (z : ZObject) : Option ZObject := z.get? "Z17K2"

/-- Accessor for key `Z17K3`. -/
def Z17.Z17K3? (z : ZObject) : Option ZObject := z.get? "Z17K3"

/-- `z` is a `Z17`/Argument: correct `Z1K1` type tag and every declared key present. -/
def isZ17 (z : ZObject) : Bool :=
  z.typeId? == some "Z17" &&
  (z.get? "Z17K1").isSome &&
  (z.get? "Z17K2").isSome &&
  (z.get? "Z17K3").isSome

/-- Self-check: the generated constructor produces a value the recognizer accepts. -/
example : isZ17 (Z17.mk (reference "Z1") (reference "Z1") (reference "Z1")) = true := by decide

end Wikifunctions.Model
