import Wikifunctions.Model.ZObject

/-! # `Z18`/Argument — AUTO-GENERATED, do not edit

Generated by `codegen/gen_type.py` from function-schemata Z18.yaml. Regenerate with
`python3 codegen/gen_type.py Z18`. Built on the hand-written `Model.ZObject` substrate. -/

namespace Wikifunctions.Model
open ZObject

/-- `Z18`/Argument smart constructor: the normal-form ZObject whose `Z1K1` tag is `reference "Z18"`. -/
def Z18.mk (z18k1 : ZObject) : ZObject :=
  node [("Z1K1", reference "Z18"), ("Z18K1", z18k1)]

/-- Accessor for key `Z18K1`. -/
def Z18.Z18K1? (z : ZObject) : Option ZObject := z.get? "Z18K1"

/-- `z` is a `Z18`/Argument: correct `Z1K1` type tag and every declared key present. -/
def isZ18 (z : ZObject) : Bool :=
  z.typeId? == some "Z18" &&
  (z.get? "Z18K1").isSome

/-- Self-check: the generated constructor produces a value the recognizer accepts. -/
example : isZ18 (Z18.mk (reference "Z1")) = true := by decide

end Wikifunctions.Model
