import Wikifunctions.Model.ZObject

/-! # `Z19677`/Rational number — AUTO-GENERATED, do not edit

Generated by `codegen/gen_type.py` from live Z4 (wikilambda_fetch). Regenerate with
`python3 codegen/gen_type.py Z19677`. Built on the hand-written `Model.ZObject` substrate. -/

namespace Wikifunctions.Model
open ZObject

/-- `Z19677`/Rational number smart constructor: the canonical-form ZObject whose `Z1K1` tag is `ref "Z19677"`. -/
def Z19677.mk (z19677k1 : ZObject) (z19677k2 : ZObject) (z19677k3 : ZObject) : ZObject :=
  node [("Z1K1", ref "Z19677"), ("Z19677K1", z19677k1), ("Z19677K2", z19677k2), ("Z19677K3", z19677k3)]

/-- Accessor for key `Z19677K1`. -/
def Z19677.Z19677K1? (z : ZObject) : Option ZObject := z.get? "Z19677K1"

/-- Accessor for key `Z19677K2`. -/
def Z19677.Z19677K2? (z : ZObject) : Option ZObject := z.get? "Z19677K2"

/-- Accessor for key `Z19677K3`. -/
def Z19677.Z19677K3? (z : ZObject) : Option ZObject := z.get? "Z19677K3"

/-- `z` is a `Z19677`/Rational number: correct `Z1K1` type tag and every declared key present. -/
def isZ19677 (z : ZObject) : Bool :=
  z.typeId? == some "Z19677" &&
  (z.get? "Z19677K1").isSome &&
  (z.get? "Z19677K2").isSome &&
  (z.get? "Z19677K3").isSome

/-- Self-check: the generated constructor produces a value the recognizer accepts. -/
example : isZ19677 (Z19677.mk (ref "Z1") (ref "Z1") (ref "Z1")) = true := by decide

end Wikifunctions.Model
