import Wikifunctions.Model.ZObject

/-! # `Z2`/Persistent — AUTO-GENERATED, do not edit

Generated by `codegen/gen_type.py` from function-schemata Z2.yaml. Regenerate with
`python3 codegen/gen_type.py Z2`. Built on the hand-written `Model.ZObject` substrate. -/

namespace Wikifunctions.Model
open ZObject

/-- `Z2`/Persistent smart constructor: the normal-form ZObject whose `Z1K1` tag is `reference "Z2"`. -/
def Z2.mk (z2k1 : ZObject) (z2k2 : ZObject) (z2k3 : ZObject) (z2k4 : ZObject) (z2k5 : ZObject) : ZObject :=
  node [("Z1K1", reference "Z2"), ("Z2K1", z2k1), ("Z2K2", z2k2), ("Z2K3", z2k3), ("Z2K4", z2k4), ("Z2K5", z2k5)]

/-- Accessor for key `Z2K1`. -/
def Z2.Z2K1? (z : ZObject) : Option ZObject := z.get? "Z2K1"

/-- Accessor for key `Z2K2`. -/
def Z2.Z2K2? (z : ZObject) : Option ZObject := z.get? "Z2K2"

/-- Accessor for key `Z2K3`. -/
def Z2.Z2K3? (z : ZObject) : Option ZObject := z.get? "Z2K3"

/-- Accessor for key `Z2K4`. -/
def Z2.Z2K4? (z : ZObject) : Option ZObject := z.get? "Z2K4"

/-- Accessor for key `Z2K5`. -/
def Z2.Z2K5? (z : ZObject) : Option ZObject := z.get? "Z2K5"

/-- `z` is a `Z2`/Persistent: correct `Z1K1` type tag and every declared key present. -/
def isZ2 (z : ZObject) : Bool :=
  z.typeId? == some "Z2" &&
  (z.get? "Z2K1").isSome &&
  (z.get? "Z2K2").isSome &&
  (z.get? "Z2K3").isSome &&
  (z.get? "Z2K4").isSome &&
  (z.get? "Z2K5").isSome

/-- Self-check: the generated constructor produces a value the recognizer accepts. -/
example : isZ2 (Z2.mk (reference "Z1") (reference "Z1") (reference "Z1") (reference "Z1") (reference "Z1")) = true := by decide

end Wikifunctions.Model
