import Wikifunctions.Model.ZObject

/-! # `Z20`/Tester — AUTO-GENERATED, do not edit

Generated by `codegen/gen_type.py` from function-schemata Z20.yaml. Regenerate with
`python3 codegen/gen_type.py Z20`. Built on the hand-written `Model.ZObject` substrate. -/

namespace Wikifunctions.Model
open ZObject

/-- `Z20`/Tester smart constructor: the canonical-form ZObject whose `Z1K1` tag is `ref "Z20"`. -/
def Z20.mk (z20k1 : ZObject) (z20k2 : ZObject) (z20k3 : ZObject) : ZObject :=
  node [("Z1K1", ref "Z20"), ("Z20K1", z20k1), ("Z20K2", z20k2), ("Z20K3", z20k3)]

/-- Accessor for key `Z20K1`. -/
def Z20.Z20K1? (z : ZObject) : Option ZObject := z.get? "Z20K1"

/-- Accessor for key `Z20K2`. -/
def Z20.Z20K2? (z : ZObject) : Option ZObject := z.get? "Z20K2"

/-- Accessor for key `Z20K3`. -/
def Z20.Z20K3? (z : ZObject) : Option ZObject := z.get? "Z20K3"

/-- `z` is a `Z20`/Tester: correct `Z1K1` type tag and every declared key present. -/
def isZ20 (z : ZObject) : Bool :=
  z.typeId? == some "Z20" &&
  (z.get? "Z20K1").isSome &&
  (z.get? "Z20K2").isSome &&
  (z.get? "Z20K3").isSome

/-- Self-check: the generated constructor produces a value the recognizer accepts. -/
example : isZ20 (Z20.mk (ref "Z1") (ref "Z1") (ref "Z1")) = true := by decide

end Wikifunctions.Model
