import Wikifunctions.Model.ZObject

/-! # `Z21`/Unit — AUTO-GENERATED, do not edit

Generated by `codegen/gen_type.py` from function-schemata Z21.yaml. Regenerate with
`python3 codegen/gen_type.py Z21`. Built on the hand-written `Model.ZObject` substrate. -/

namespace Wikifunctions.Model
open ZObject

/-- `Z21`/Unit smart constructor: the normal-form ZObject whose `Z1K1` tag is `reference "Z21"`. -/
def Z21.mk : ZObject :=
  node [("Z1K1", reference "Z21")]

-- (no data keys)

/-- `z` is a `Z21`/Unit: correct `Z1K1` type tag and every declared key present. -/
def isZ21 (z : ZObject) : Bool :=
  z.typeId? == some "Z21"

/-- Self-check: the generated constructor produces a value the recognizer accepts. -/
example : isZ21 (Z21.mk) = true := by decide

end Wikifunctions.Model
