import Wikifunctions.Model.ZObject

/-! # `Z22`/Evaluation — AUTO-GENERATED, do not edit

Generated by `codegen/gen_type.py` from function-schemata Z22.yaml. Regenerate with
`python3 codegen/gen_type.py Z22`. Built on the hand-written `Model.ZObject` substrate. -/

namespace Wikifunctions.Model
open ZObject

/-- `Z22`/Evaluation smart constructor: the canonical-form ZObject whose `Z1K1` tag is `ref "Z22"`. -/
def Z22.mk (z22k1 : ZObject) (z22k2 : ZObject) : ZObject :=
  node [("Z1K1", ref "Z22"), ("Z22K1", z22k1), ("Z22K2", z22k2)]

/-- Accessor for key `Z22K1`. -/
def Z22.Z22K1? (z : ZObject) : Option ZObject := z.get? "Z22K1"

/-- Accessor for key `Z22K2`. -/
def Z22.Z22K2? (z : ZObject) : Option ZObject := z.get? "Z22K2"

/-- `z` is a `Z22`/Evaluation: correct `Z1K1` type tag and every declared key present. -/
def isZ22 (z : ZObject) : Bool :=
  z.typeId? == some "Z22" &&
  (z.get? "Z22K1").isSome &&
  (z.get? "Z22K2").isSome

/-- Self-check: the generated constructor produces a value the recognizer accepts. -/
example : isZ22 (Z22.mk (ref "Z1") (ref "Z1")) = true := by decide

end Wikifunctions.Model
