import Wikifunctions.Model.ZObject

/-! # `Z23`/Nothing — AUTO-GENERATED, do not edit

Generated by `codegen/gen_type.py` from live Z4 (wikilambda_fetch). Regenerate with
`python3 codegen/gen_type.py Z23`. Built on the hand-written `Model.ZObject` substrate. -/

namespace Wikifunctions.Model
open ZObject

/-- `Z23`/Nothing smart constructor: the canonical-form ZObject whose `Z1K1` tag is `ref "Z23"`. -/
def Z23.mk : ZObject :=
  node [("Z1K1", ref "Z23")]

-- (no data keys)

/-- `z` is a `Z23`/Nothing: correct `Z1K1` type tag and every declared key present. -/
def isZ23 (z : ZObject) : Bool :=
  z.typeId? == some "Z23"

/-- Self-check: the generated constructor produces a value the recognizer accepts. -/
example : isZ23 (Z23.mk) = true := by decide

end Wikifunctions.Model
