import Wikifunctions.Model.ZObject

/-! # `Z3`/Key — AUTO-GENERATED, do not edit

Generated by `codegen/gen_type.py` from function-schemata Z3.yaml. Regenerate with
`python3 codegen/gen_type.py Z3`. Built on the hand-written `Model.ZObject` substrate. -/

namespace Wikifunctions.Model
open ZObject

/-- `Z3`/Key smart constructor: the canonical-form ZObject whose `Z1K1` tag is `ref "Z3"`. -/
def Z3.mk (z3k1 : ZObject) (z3k2 : ZObject) (z3k3 : ZObject) (z3k4 : ZObject) : ZObject :=
  node [("Z1K1", ref "Z3"), ("Z3K1", z3k1), ("Z3K2", z3k2), ("Z3K3", z3k3), ("Z3K4", z3k4)]

/-- Accessor for key `Z3K1`. -/
def Z3.Z3K1? (z : ZObject) : Option ZObject := z.get? "Z3K1"

/-- Accessor for key `Z3K2`. -/
def Z3.Z3K2? (z : ZObject) : Option ZObject := z.get? "Z3K2"

/-- Accessor for key `Z3K3`. -/
def Z3.Z3K3? (z : ZObject) : Option ZObject := z.get? "Z3K3"

/-- Accessor for key `Z3K4`. -/
def Z3.Z3K4? (z : ZObject) : Option ZObject := z.get? "Z3K4"

/-- `z` is a `Z3`/Key: correct `Z1K1` type tag and every declared key present. -/
def isZ3 (z : ZObject) : Bool :=
  z.typeId? == some "Z3" &&
  (z.get? "Z3K1").isSome &&
  (z.get? "Z3K2").isSome &&
  (z.get? "Z3K3").isSome &&
  (z.get? "Z3K4").isSome

/-- Self-check: the generated constructor produces a value the recognizer accepts. -/
example : isZ3 (Z3.mk (ref "Z1") (ref "Z1") (ref "Z1") (ref "Z1")) = true := by decide

end Wikifunctions.Model
