import Wikifunctions.Model.ZObject

/-! # `Z31`/MonoLingualStringSet — AUTO-GENERATED, do not edit

Generated by `codegen/gen_type.py` from function-schemata Z31.yaml. Regenerate with
`python3 codegen/gen_type.py Z31`. Built on the hand-written `Model.ZObject` substrate. -/

namespace Wikifunctions.Model
open ZObject

/-- `Z31`/MonoLingualStringSet smart constructor: the canonical-form ZObject whose `Z1K1` tag is `ref "Z31"`. -/
def Z31.mk (z31k1 : ZObject) (z31k2 : ZObject) : ZObject :=
  node [("Z1K1", ref "Z31"), ("Z31K1", z31k1), ("Z31K2", z31k2)]

/-- Accessor for key `Z31K1`. -/
def Z31.Z31K1? (z : ZObject) : Option ZObject := z.get? "Z31K1"

/-- Accessor for key `Z31K2`. -/
def Z31.Z31K2? (z : ZObject) : Option ZObject := z.get? "Z31K2"

/-- `z` is a `Z31`/MonoLingualStringSet: correct `Z1K1` type tag and every declared key present. -/
def isZ31 (z : ZObject) : Bool :=
  z.typeId? == some "Z31" &&
  (z.get? "Z31K1").isSome &&
  (z.get? "Z31K2").isSome

/-- Self-check: the generated constructor produces a value the recognizer accepts. -/
example : isZ31 (Z31.mk (ref "Z1") (ref "Z1")) = true := by decide

end Wikifunctions.Model
