import Wikifunctions.Model.ZObject

/-! # `Z32`/MultiLingualStringSet — AUTO-GENERATED, do not edit

Generated by `codegen/gen_type.py` from function-schemata Z32.yaml. Regenerate with
`python3 codegen/gen_type.py Z32`. Built on the hand-written `Model.ZObject` substrate. -/

namespace Wikifunctions.Model
open ZObject

/-- `Z32`/MultiLingualStringSet smart constructor: the canonical-form ZObject whose `Z1K1` tag is `ref "Z32"`. -/
def Z32.mk (z32k1 : ZObject) : ZObject :=
  node [("Z1K1", ref "Z32"), ("Z32K1", z32k1)]

/-- Accessor for key `Z32K1`. -/
def Z32.Z32K1? (z : ZObject) : Option ZObject := z.get? "Z32K1"

/-- `z` is a `Z32`/MultiLingualStringSet: correct `Z1K1` type tag and every declared key present. -/
def isZ32 (z : ZObject) : Bool :=
  z.typeId? == some "Z32" &&
  (z.get? "Z32K1").isSome

/-- Self-check: the generated constructor produces a value the recognizer accepts. -/
example : isZ32 (Z32.mk (ref "Z1")) = true := by decide

end Wikifunctions.Model
