import Wikifunctions.Model.ZObject

/-! # `Z39`/Key — AUTO-GENERATED, do not edit

Generated by `codegen/gen_type.py` from function-schemata Z39.yaml. Regenerate with
`python3 codegen/gen_type.py Z39`. Built on the hand-written `Model.ZObject` substrate. -/

namespace Wikifunctions.Model
open ZObject

/-- `Z39`/Key smart constructor: the canonical-form ZObject whose `Z1K1` tag is `ref "Z39"`. -/
def Z39.mk (z39k1 : ZObject) : ZObject :=
  node [("Z1K1", ref "Z39"), ("Z39K1", z39k1)]

/-- Accessor for key `Z39K1`. -/
def Z39.Z39K1? (z : ZObject) : Option ZObject := z.get? "Z39K1"

/-- `z` is a `Z39`/Key: correct `Z1K1` type tag and every declared key present. -/
def isZ39 (z : ZObject) : Bool :=
  z.typeId? == some "Z39" &&
  (z.get? "Z39K1").isSome

/-- Self-check: the generated constructor produces a value the recognizer accepts. -/
example : isZ39 (Z39.mk (ref "Z1")) = true := by decide

end Wikifunctions.Model
