import Wikifunctions.Model.ZObject

/-! # `Z4`/Type — AUTO-GENERATED, do not edit

Generated by `codegen/gen_type.py` from function-schemata Z4.yaml. Regenerate with
`python3 codegen/gen_type.py Z4`. Built on the hand-written `Model.ZObject` substrate. -/

namespace Wikifunctions.Model
open ZObject

/-- `Z4`/Type smart constructor: the normal-form ZObject with tag `Z4`. -/
def Z4.mk (z4k1 : ZObject) (z4k2 : ZObject) (z4k3 : ZObject) (z4k4 : ZObject) (z4k5 : ZObject) (z4k6 : ZObject) (z4k7 : ZObject) (z4k8 : ZObject) : ZObject :=
  node [("Z1K1", reference "Z4"), ("Z4K1", z4k1), ("Z4K2", z4k2), ("Z4K3", z4k3), ("Z4K4", z4k4), ("Z4K5", z4k5), ("Z4K6", z4k6), ("Z4K7", z4k7), ("Z4K8", z4k8)]

/-- Accessor for key `Z4K1`. -/
def Z4.Z4K1? (z : ZObject) : Option ZObject := z.get? "Z4K1"

/-- Accessor for key `Z4K2`. -/
def Z4.Z4K2? (z : ZObject) : Option ZObject := z.get? "Z4K2"

/-- Accessor for key `Z4K3`. -/
def Z4.Z4K3? (z : ZObject) : Option ZObject := z.get? "Z4K3"

/-- Accessor for key `Z4K4`. -/
def Z4.Z4K4? (z : ZObject) : Option ZObject := z.get? "Z4K4"

/-- Accessor for key `Z4K5`. -/
def Z4.Z4K5? (z : ZObject) : Option ZObject := z.get? "Z4K5"

/-- Accessor for key `Z4K6`. -/
def Z4.Z4K6? (z : ZObject) : Option ZObject := z.get? "Z4K6"

/-- Accessor for key `Z4K7`. -/
def Z4.Z4K7? (z : ZObject) : Option ZObject := z.get? "Z4K7"

/-- Accessor for key `Z4K8`. -/
def Z4.Z4K8? (z : ZObject) : Option ZObject := z.get? "Z4K8"

/-- `z` is a `Z4`/Type: correct `Z1K1` type tag and every declared key present. -/
def isZ4 (z : ZObject) : Bool :=
  z.typeId? == some "Z4" &&
  (z.get? "Z4K1").isSome &&
  (z.get? "Z4K2").isSome &&
  (z.get? "Z4K3").isSome &&
  (z.get? "Z4K4").isSome &&
  (z.get? "Z4K5").isSome &&
  (z.get? "Z4K6").isSome &&
  (z.get? "Z4K7").isSome &&
  (z.get? "Z4K8").isSome

/-- Self-check: the generated constructor produces a value the recognizer accepts. -/
example : isZ4 (Z4.mk (reference "Z1") (reference "Z1") (reference "Z1") (reference "Z1") (reference "Z1") (reference "Z1") (reference "Z1") (reference "Z1")) = true := by decide

end Wikifunctions.Model
