import Wikifunctions.Model.ZObject

/-! # `Z40`/Boolean — AUTO-GENERATED, do not edit

Generated by `codegen/gen_type.py` from function-schemata Z40.yaml. Regenerate with
`python3 codegen/gen_type.py Z40`. Built on the hand-written `Model.ZObject` substrate. -/

namespace Wikifunctions.Model
open ZObject

/-- `Z40`/Boolean smart constructor: the canonical-form ZObject whose `Z1K1` tag is `ref "Z40"`. -/
def Z40.mk (z40k1 : ZObject) : ZObject :=
  node [("Z1K1", ref "Z40"), ("Z40K1", z40k1)]

/-- Accessor for key `Z40K1`. -/
def Z40.Z40K1? (z : ZObject) : Option ZObject := z.get? "Z40K1"

/-- `z` is a `Z40`/Boolean: correct `Z1K1` type tag and every declared key present. -/
def isZ40 (z : ZObject) : Bool :=
  z.typeId? == some "Z40" &&
  (z.get? "Z40K1").isSome

/-- Self-check: the generated constructor produces a value the recognizer accepts. -/
example : isZ40 (Z40.mk (ref "Z1")) = true := by decide

end Wikifunctions.Model
