import Wikifunctions.Model.ZObject

/-! # `Z46`/Type — AUTO-GENERATED, do not edit

Generated by `codegen/gen_type.py` from function-schemata Z46.yaml. Regenerate with
`python3 codegen/gen_type.py Z46`. Built on the hand-written `Model.ZObject` substrate. -/

namespace Wikifunctions.Model
open ZObject

/-- `Z46`/Type smart constructor: the normal-form ZObject whose `Z1K1` tag is `reference "Z46"`. -/
def Z46.mk (z46k1 : ZObject) (z46k2 : ZObject) (z46k3 : ZObject) (z46k4 : ZObject) : ZObject :=
  node [("Z1K1", reference "Z46"), ("Z46K1", z46k1), ("Z46K2", z46k2), ("Z46K3", z46k3), ("Z46K4", z46k4)]

/-- Accessor for key `Z46K1`. -/
def Z46.Z46K1? (z : ZObject) : Option ZObject := z.get? "Z46K1"

/-- Accessor for key `Z46K2`. -/
def Z46.Z46K2? (z : ZObject) : Option ZObject := z.get? "Z46K2"

/-- Accessor for key `Z46K3`. -/
def Z46.Z46K3? (z : ZObject) : Option ZObject := z.get? "Z46K3"

/-- Accessor for key `Z46K4`. -/
def Z46.Z46K4? (z : ZObject) : Option ZObject := z.get? "Z46K4"

/-- `z` is a `Z46`/Type: correct `Z1K1` type tag and every declared key present. -/
def isZ46 (z : ZObject) : Bool :=
  z.typeId? == some "Z46" &&
  (z.get? "Z46K1").isSome &&
  (z.get? "Z46K2").isSome &&
  (z.get? "Z46K3").isSome &&
  (z.get? "Z46K4").isSome

/-- Self-check: the generated constructor produces a value the recognizer accepts. -/
example : isZ46 (Z46.mk (reference "Z1") (reference "Z1") (reference "Z1") (reference "Z1")) = true := by decide

end Wikifunctions.Model
