import Wikifunctions.Model.ZObject

/-! # `Z5`/Error — AUTO-GENERATED, do not edit

Generated by `codegen/gen_type.py` from function-schemata Z5.yaml. Regenerate with
`python3 codegen/gen_type.py Z5`. Built on the hand-written `Model.ZObject` substrate. -/

namespace Wikifunctions.Model
open ZObject

/-- `Z5`/Error smart constructor: the normal-form ZObject with tag `Z5`. -/
def Z5.mk (z5k1 : ZObject) (z5k2 : ZObject) : ZObject :=
  node [("Z1K1", reference "Z5"), ("Z5K1", z5k1), ("Z5K2", z5k2)]

/-- Accessor for key `Z5K1`. -/
def Z5.Z5K1? (z : ZObject) : Option ZObject := z.get? "Z5K1"

/-- Accessor for key `Z5K2`. -/
def Z5.Z5K2? (z : ZObject) : Option ZObject := z.get? "Z5K2"

/-- `z` is a `Z5`/Error: correct `Z1K1` type tag and every declared key present. -/
def isZ5 (z : ZObject) : Bool :=
  z.typeId? == some "Z5" &&
  (z.get? "Z5K1").isSome &&
  (z.get? "Z5K2").isSome

/-- Self-check: the generated constructor produces a value the recognizer accepts. -/
example : isZ5 (Z5.mk (reference "Z1") (reference "Z1")) = true := by decide

end Wikifunctions.Model
