import Wikifunctions.Model.ZObject

/-! # `Z50`/Error — AUTO-GENERATED, do not edit

Generated by `codegen/gen_type.py` from function-schemata Z50.yaml. Regenerate with
`python3 codegen/gen_type.py Z50`. Built on the hand-written `Model.ZObject` substrate. -/

namespace Wikifunctions.Model
open ZObject

/-- `Z50`/Error smart constructor: the canonical-form ZObject whose `Z1K1` tag is `ref "Z50"`. -/
def Z50.mk (z50k1 : ZObject) (z50k2 : ZObject) : ZObject :=
  node [("Z1K1", ref "Z50"), ("Z50K1", z50k1), ("Z50K2", z50k2)]

/-- Accessor for key `Z50K1`. -/
def Z50.Z50K1? (z : ZObject) : Option ZObject := z.get? "Z50K1"

/-- Accessor for key `Z50K2`. -/
def Z50.Z50K2? (z : ZObject) : Option ZObject := z.get? "Z50K2"

/-- `z` is a `Z50`/Error: correct `Z1K1` type tag and every declared key present. -/
def isZ50 (z : ZObject) : Bool :=
  z.typeId? == some "Z50" &&
  (z.get? "Z50K1").isSome &&
  (z.get? "Z50K2").isSome

/-- Self-check: the generated constructor produces a value the recognizer accepts. -/
example : isZ50 (Z50.mk (ref "Z1") (ref "Z1")) = true := by decide

end Wikifunctions.Model
