import Wikifunctions.Model.ZObject

/-! # `Z60`/Language — AUTO-GENERATED, do not edit

Generated by `codegen/gen_type.py` from function-schemata Z60.yaml. Regenerate with
`python3 codegen/gen_type.py Z60`. Built on the hand-written `Model.ZObject` substrate. -/

namespace Wikifunctions.Model
open ZObject

/-- `Z60`/Language smart constructor: the normal-form ZObject with tag `Z60`. -/
def Z60.mk (z60k1 : ZObject) (z60k2 : ZObject) : ZObject :=
  node [("Z1K1", reference "Z60"), ("Z60K1", z60k1), ("Z60K2", z60k2)]

/-- Accessor for key `Z60K1`. -/
def Z60.Z60K1? (z : ZObject) : Option ZObject := z.get? "Z60K1"

/-- Accessor for key `Z60K2`. -/
def Z60.Z60K2? (z : ZObject) : Option ZObject := z.get? "Z60K2"

/-- `z` is a `Z60`/Language: correct `Z1K1` type tag and every declared key present. -/
def isZ60 (z : ZObject) : Bool :=
  z.typeId? == some "Z60" &&
  (z.get? "Z60K1").isSome &&
  (z.get? "Z60K2").isSome

/-- Self-check: the generated constructor produces a value the recognizer accepts. -/
example : isZ60 (Z60.mk (reference "Z1") (reference "Z1")) = true := by decide

end Wikifunctions.Model
