import Wikifunctions.Model.ZObject

/-! # `Z6040`/Wikidata — AUTO-GENERATED, do not edit

Generated by `codegen/gen_type.py` from function-schemata Z6040.yaml. Regenerate with
`python3 codegen/gen_type.py Z6040`. Built on the hand-written `Model.ZObject` substrate. -/

namespace Wikifunctions.Model
open ZObject

/-- `Z6040`/Wikidata smart constructor: the normal-form ZObject whose `Z1K1` tag is `reference "Z6040"`. -/
def Z6040.mk (z6040k1 : ZObject) : ZObject :=
  node [("Z1K1", reference "Z6040"), ("Z6040K1", z6040k1)]

/-- Accessor for key `Z6040K1`. -/
def Z6040.Z6040K1? (z : ZObject) : Option ZObject := z.get? "Z6040K1"

/-- `z` is a `Z6040`/Wikidata: correct `Z1K1` type tag and every declared key present. -/
def isZ6040 (z : ZObject) : Bool :=
  z.typeId? == some "Z6040" &&
  (z.get? "Z6040K1").isSome

/-- Self-check: the generated constructor produces a value the recognizer accepts. -/
example : isZ6040 (Z6040.mk (reference "Z1")) = true := by decide

end Wikifunctions.Model
