import Wikifunctions.Model.ZObject

/-! # `Z61`/Programming — AUTO-GENERATED, do not edit

Generated by `codegen/gen_type.py` from function-schemata Z61.yaml. Regenerate with
`python3 codegen/gen_type.py Z61`. Built on the hand-written `Model.ZObject` substrate. -/

namespace Wikifunctions.Model
open ZObject

/-- `Z61`/Programming smart constructor: the canonical-form ZObject whose `Z1K1` tag is `ref "Z61"`. -/
def Z61.mk (z61k1 : ZObject) : ZObject :=
  node [("Z1K1", ref "Z61"), ("Z61K1", z61k1)]

/-- Accessor for key `Z61K1`. -/
def Z61.Z61K1? (z : ZObject) : Option ZObject := z.get? "Z61K1"

/-- `z` is a `Z61`/Programming: correct `Z1K1` type tag and every declared key present. -/
def isZ61 (z : ZObject) : Bool :=
  z.typeId? == some "Z61" &&
  (z.get? "Z61K1").isSome

/-- Self-check: the generated constructor produces a value the recognizer accepts. -/
example : isZ61 (Z61.mk (ref "Z1")) = true := by decide

end Wikifunctions.Model
