import Wikifunctions.Model.ZObject

/-! # `Z64`/Type — AUTO-GENERATED, do not edit

Generated by `codegen/gen_type.py` from function-schemata Z64.yaml. Regenerate with
`python3 codegen/gen_type.py Z64`. Built on the hand-written `Model.ZObject` substrate. -/

namespace Wikifunctions.Model
open ZObject

/-- `Z64`/Type smart constructor: the canonical-form ZObject whose `Z1K1` tag is `ref "Z64"`. -/
def Z64.mk (z64k1 : ZObject) (z64k2 : ZObject) (z64k3 : ZObject) (z64k4 : ZObject) : ZObject :=
  node [("Z1K1", ref "Z64"), ("Z64K1", z64k1), ("Z64K2", z64k2), ("Z64K3", z64k3), ("Z64K4", z64k4)]

/-- Accessor for key `Z64K1`. -/
def Z64.Z64K1? (z : ZObject) : Option ZObject := z.get? "Z64K1"

/-- Accessor for key `Z64K2`. -/
def Z64.Z64K2? (z : ZObject) : Option ZObject := z.get? "Z64K2"

/-- Accessor for key `Z64K3`. -/
def Z64.Z64K3? (z : ZObject) : Option ZObject := z.get? "Z64K3"

/-- Accessor for key `Z64K4`. -/
def Z64.Z64K4? (z : ZObject) : Option ZObject := z.get? "Z64K4"

/-- `z` is a `Z64`/Type: correct `Z1K1` type tag and every declared key present. -/
def isZ64 (z : ZObject) : Bool :=
  z.typeId? == some "Z64" &&
  (z.get? "Z64K1").isSome &&
  (z.get? "Z64K2").isSome &&
  (z.get? "Z64K3").isSome &&
  (z.get? "Z64K4").isSome

/-- Self-check: the generated constructor produces a value the recognizer accepts. -/
example : isZ64 (Z64.mk (ref "Z1") (ref "Z1") (ref "Z1") (ref "Z1")) = true := by decide

end Wikifunctions.Model
