import Wikifunctions.Model.ZObject

/-! # `Z7`/Function — AUTO-GENERATED, do not edit

Generated by `codegen/gen_type.py` from function-schemata Z7.yaml. Regenerate with
`python3 codegen/gen_type.py Z7`. Built on the hand-written `Model.ZObject` substrate. -/

namespace Wikifunctions.Model
open ZObject

/-- `Z7`/Function smart constructor: the normal-form ZObject with tag `Z7`. -/
def Z7.mk (z7k1 : ZObject) : ZObject :=
  node [("Z1K1", reference "Z7"), ("Z7K1", z7k1)]

/-- Accessor for key `Z7K1`. -/
def Z7.Z7K1? (z : ZObject) : Option ZObject := z.get? "Z7K1"

/-- `z` is a `Z7`/Function: correct `Z1K1` type tag and every declared key present. -/
def isZ7 (z : ZObject) : Bool :=
  z.typeId? == some "Z7" &&
  (z.get? "Z7K1").isSome

/-- Self-check: the generated constructor produces a value the recognizer accepts. -/
example : isZ7 (Z7.mk (reference "Z1")) = true := by decide

end Wikifunctions.Model
