import Wikifunctions.Model.ZObject

/-! # `Z8`/Function — AUTO-GENERATED, do not edit

Generated by `codegen/gen_type.py` from function-schemata Z8.yaml. Regenerate with
`python3 codegen/gen_type.py Z8`. Built on the hand-written `Model.ZObject` substrate. -/

namespace Wikifunctions.Model
open ZObject

/-- `Z8`/Function smart constructor: the normal-form ZObject whose `Z1K1` tag is `reference "Z8"`. -/
def Z8.mk (z8k1 : ZObject) (z8k2 : ZObject) (z8k3 : ZObject) (z8k4 : ZObject) (z8k5 : ZObject) : ZObject :=
  node [("Z1K1", reference "Z8"), ("Z8K1", z8k1), ("Z8K2", z8k2), ("Z8K3", z8k3), ("Z8K4", z8k4), ("Z8K5", z8k5)]

/-- Accessor for key `Z8K1`. -/
def Z8.Z8K1? (z : ZObject) : Option ZObject := z.get? "Z8K1"

/-- Accessor for key `Z8K2`. -/
def Z8.Z8K2? (z : ZObject) : Option ZObject := z.get? "Z8K2"

/-- Accessor for key `Z8K3`. -/
def Z8.Z8K3? (z : ZObject) : Option ZObject := z.get? "Z8K3"

/-- Accessor for key `Z8K4`. -/
def Z8.Z8K4? (z : ZObject) : Option ZObject := z.get? "Z8K4"

/-- Accessor for key `Z8K5`. -/
def Z8.Z8K5? (z : ZObject) : Option ZObject := z.get? "Z8K5"

/-- `z` is a `Z8`/Function: correct `Z1K1` type tag and every declared key present. -/
def isZ8 (z : ZObject) : Bool :=
  z.typeId? == some "Z8" &&
  (z.get? "Z8K1").isSome &&
  (z.get? "Z8K2").isSome &&
  (z.get? "Z8K3").isSome &&
  (z.get? "Z8K4").isSome &&
  (z.get? "Z8K5").isSome

/-- Self-check: the generated constructor produces a value the recognizer accepts. -/
example : isZ8 (Z8.mk (reference "Z1") (reference "Z1") (reference "Z1") (reference "Z1") (reference "Z1")) = true := by decide

end Wikifunctions.Model
