import Wikifunctions.Model.ZObject

/-! # `Z80`/Byte — AUTO-GENERATED, do not edit

Generated by `codegen/gen_type.py` from function-schemata Z80.yaml. Regenerate with
`python3 codegen/gen_type.py Z80`. Built on the hand-written `Model.ZObject` substrate. -/

namespace Wikifunctions.Model
open ZObject

/-- `Z80`/Byte smart constructor: the normal-form ZObject whose `Z1K1` tag is `reference "Z80"`. -/
def Z80.mk (z80k1 : ZObject) : ZObject :=
  node [("Z1K1", reference "Z80"), ("Z80K1", z80k1)]

/-- Accessor for key `Z80K1`. -/
def Z80.Z80K1? (z : ZObject) : Option ZObject := z.get? "Z80K1"

/-- `z` is a `Z80`/Byte: correct `Z1K1` type tag and every declared key present. -/
def isZ80 (z : ZObject) : Bool :=
  z.typeId? == some "Z80" &&
  (z.get? "Z80K1").isSome

/-- Self-check: the generated constructor produces a value the recognizer accepts. -/
example : isZ80 (Z80.mk (reference "Z1")) = true := by decide

end Wikifunctions.Model
