import Wikifunctions.Model.ZObject

/-! # `Z86`/Code — AUTO-GENERATED, do not edit

Generated by `codegen/gen_type.py` from function-schemata Z86.yaml. Regenerate with
`python3 codegen/gen_type.py Z86`. Built on the hand-written `Model.ZObject` substrate. -/

namespace Wikifunctions.Model
open ZObject

/-- `Z86`/Code smart constructor: the normal-form ZObject with tag `Z86`. -/
def Z86.mk (z86k1 : ZObject) : ZObject :=
  node [("Z1K1", reference "Z86"), ("Z86K1", z86k1)]

/-- Accessor for key `Z86K1`. -/
def Z86.Z86K1? (z : ZObject) : Option ZObject := z.get? "Z86K1"

/-- `z` is a `Z86`/Code: correct `Z1K1` type tag and every declared key present. -/
def isZ86 (z : ZObject) : Bool :=
  z.typeId? == some "Z86" &&
  (z.get? "Z86K1").isSome

/-- Self-check: the generated constructor produces a value the recognizer accepts. -/
example : isZ86 (Z86.mk (reference "Z1")) = true := by decide

end Wikifunctions.Model
