import Wikifunctions.Model.ZObject

/-! # `Z99`/Quote — AUTO-GENERATED, do not edit

Generated by `codegen/gen_type.py` from function-schemata Z99.yaml. Regenerate with
`python3 codegen/gen_type.py Z99`. Built on the hand-written `Model.ZObject` substrate. -/

namespace Wikifunctions.Model
open ZObject

/-- `Z99`/Quote smart constructor: the normal-form ZObject with tag `Z99`. -/
def Z99.mk (z99k1 : ZObject) : ZObject :=
  node [("Z1K1", reference "Z99"), ("Z99K1", z99k1)]

/-- Accessor for key `Z99K1`. -/
def Z99.Z99K1? (z : ZObject) : Option ZObject := z.get? "Z99K1"

/-- `z` is a `Z99`/Quote: correct `Z1K1` type tag and every declared key present. -/
def isZ99 (z : ZObject) : Bool :=
  z.typeId? == some "Z99" &&
  (z.get? "Z99K1").isSome

/-- Self-check: the generated constructor produces a value the recognizer accepts. -/
example : isZ99 (Z99.mk (reference "Z1")) = true := by decide

end Wikifunctions.Model
